"use client";
import React, { useState, useEffect } from "react";
import { base64ToBlob } from "@/lib/utils";

interface MirrorProps {
  userPhoto: File | string;
  productPhoto: File | string;
  prompt: string;
}

export default function Mirror({ userPhoto, productPhoto, prompt }: MirrorProps) {
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleTryOn() {
    if (!userPhoto || !productPhoto) return;

    setLoading(true);
    setError(null);

    try {
      const formData = new FormData();

      // Handle User Photo
      if (typeof userPhoto === 'string') {
        const blob = base64ToBlob(userPhoto);
        formData.append("image1", blob, "user-photo.jpg");
      } else {
        formData.append("image1", userPhoto);
      }

      // Handle Product Photo
      if (typeof productPhoto === 'string') {
        const blob = base64ToBlob(productPhoto);
        formData.append("image2", blob, "product-photo.jpg");
      } else {
        formData.append("image2", productPhoto);
      }

      formData.append("prompt", prompt);

      const response = await fetch("/api/gen", { 
        method: "POST",
        body: formData,
      });

      const data = await response.json();

      if (!response.ok) throw new Error(data.error || "Generation failed");

      if (data.result) {
        // Ensure result is a valid Data URL if it isn't already
        const finalImageSrc = data.result.startsWith('data:')
            ? data.result
            : `data:image/png;base64,${data.result}`;
        setGeneratedImage(finalImageSrc);
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  // Trigger generation on mount or when props change
  // We might want to make this manual to avoid auto-generating if the user hasn't confirmed
  // But the requirement implies "what a user sees is them wearing the clothing",
  // suggesting it might be the default view or highly prominent.
  // For now, let's keep it automatic if props are present, but maybe we should expose the generated image up?
  // Actually, the requirement says "The true product image is to be displayed below the main full image of the user wearing the clothing generated by the mirror component."
  // So this component should probably display the generated image.

  useEffect(() => {
    handleTryOn();
  }, [userPhoto, productPhoto, prompt]);

  if (loading) {
    return (
        <div className="w-full h-full min-h-[400px] flex flex-col items-center justify-center bg-[var(--color-secondary)] rounded-[var(--radius-xl)] border border-[var(--color-border)] animate-pulse">
            <div className="text-[var(--color-primary)] text-xl font-bold mb-2">Generating Try-On...</div>
            <div className="text-[var(--color-subtle-text)] text-sm">Weaving digital threads</div>
        </div>
    );
  }

  if (error) {
     // If error, we might just return null or a simple message so the parent can fallback to product image
     return (
        <div className="w-full h-full min-h-[400px] flex flex-col items-center justify-center bg-[var(--color-card)] rounded-[var(--radius-xl)] border border-red-900/50 p-6 text-center">
            <p className="text-red-500 font-bold mb-2">Couldn't generate try-on</p>
            <p className="text-xs text-[var(--color-subtle-text)]">{error}</p>
        </div>
     );
  }

  if (generatedImage) {
      return (
        <div className="relative w-full h-full min-h-[400px] lg:min-h-[600px] rounded-[var(--radius-xl)] overflow-hidden border border-[var(--color-primary)] shadow-[0_0_40px_-10px_rgba(255,214,10,0.3)]">
            <img src={generatedImage} alt="Virtual Try-On" className="w-full h-full object-cover" />
            <div className="absolute top-4 right-4 tw-tag bg-black/80 text-[var(--color-primary)] border border-[var(--color-primary)]">
                ✨ AI Mirror
            </div>
        </div>
      );
  }

  return null;
}
